#set style line 1 lt 1 lw 8
#set style line 2 lt 3 lw 8
#set style line 3 lt 1 lw 2
#set style line 4 lt 3 lw 2
#set style line 5 lt 0 lw 8
#set style line 6 lt 0 lw 4

set pointsize 2

# BLUE   -> #0066CC
# RED    -> #993333
# GREEN  -> #006633
# PURPLE -> #663399
# ORANGE -> #CC6633

# HTM
set style line 1 lt 1 lc rgb "#CC6633" lw 3 pt 7  ps 2.5 dt 1
# HEWRL
set style line 2 lt 1 lc rgb "#CC6633" lw 3 pt 7  ps 2.5 dt (4,2)
# BRLock
set style line 3 lt 4 lc rgb "black" lw 3  pt 11 ps 2.5 dt 1
# RWL
set style line 4 lt 4 lc rgb "black" lw 3  pt 11 ps 2.5 dt (4,2)
# NoWait
set style line 5 lt 1 lc rgb "#663399" lw 3 pt 7  ps 2.5 dt 1
# Alpha
set style line 6 lt 1 lc rgb "#663399" lw 3 pt 7  ps 2.5 dt (4,2)
# overlap
set style line 7 lt 1 lc rgb "#0066CC" lw 3 pt 9  ps 2.5 dt 1
# hoverlap
set style line 8 lt 1 lc rgb "#0066CC" lw 3 pt 9  ps 2.5 dt (4,2)
# snzi
set style line 9 lt 2 lc rgb "#993333" lw 3 pt 11 ps 2.5 dt 1
# hsnzi
set style line 10 lt 2 lc rgb "#993333" lw 3 pt 11 ps 2.5 dt (4,2)
# oswc
set style line 11 lt 1 lc rgb "yellow" lw 3 pt 3  ps 2.5 dt 1


