CFLAGS   += -w $(HTM_RETRIES) $(RETRY_POLICY)

CPPFLAGS := $(CFLAGS)
LIBS     += $(CFLAGS) -I ../../../stms/tl2/ -lrt -mcpu=power8 -mtune=power8 -lm -L../../../stms/tl2/ -ltl2 -lpthread -lm
LDFLAGS  += $(LIBS)
