CFLAGS   += -w -DSTM -I$(STM)/include -DPTM -O2 --std=c++17 -g -fPIC -DCLFLUSH -DMIN_BACKOFF=2
LIBS     += $(CPPFLAGS) -lstm -lm -ltcmalloc -lrt -lpthread -fpermissive
CC       = g++
uname_p := $(shell uname -p)
ifeq ($(uname_p),x86_64)
CFLAGS   += -mrtm -mcpu=native -mtune=native 
LIBS     += 
else
CFLAGS   += -mhtm -mcpu=native -mtune=native -DNO_WARN_X86_INTRINSICS
LIBS     += -mcpu=power9 -mtune=power9
endif

CPPFLAGS := $(CFLAGS)
LDFLAGS  += -L$(STM)/lib

